# -*- coding: utf-8 -*-
"""herokusample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i31icWCGy1ovsYxIp7pIaVDwNQyZTeuj
"""







from flask import Flask,render_template,request

app=Flask(__name__)
@app.route('/')
def home():
  return "<h1>Hii my name is akshay sutar</h1>"


if __name__=='__main__':
  app.run()

